### ISSUE TITLE
[tf2]Does kernel size=(1, 1) work ?

### ISSUE THREAD

**Issue by haihai-self** [ehw-fit/tf-approximate#12]
Hi, my name is hai-hai
Thank you for your opening source very much.
I tried to work on resnet54, but found that aproximate result is greatly affect when the kernel=(1 ,1), such as FakeApproxConv2D(kernel_size=(1,1)), I want to know whether the convolution behavior is defined when kernel=(1, 1). 
Look forward to your answer and best wish

**Comment by mrazekv** [comment]
Hi hai-hai,
thank you for your interest in this library.

Part with `kernel_size=(1. 1)` may have a bug in the implementation. You can try to comment on these lines [tf2/src/approx_nn_conv_ops.cpp lines 538 - 580](https://github.com/ehw-fit/tf-approximate/blob/master/tf2/src/approx_nn_conv_ops.cpp#L538-L580)

This part of the code speeds up the evaluation where full GEMM is not needed. However, there may be some bug.

Did it help?
Vojta

**Comment by mhsamavatian** [comment]
Yes, that part of the code is buggy. Without that it works.
