### ISSUE TITLE
Problem in using the singularity container

### ISSUE THREAD

**Issue by ayeshamkzhh** [ehw-fit/tf-approximate#13]
Hi! I tried to use the singularity container with the following command on Ubuntu 20.04 (installed inside Windows machine).
`singularity shell -H $(pwd) --nv --bind . ../../tf-approximate-gpu.sif
`
However, it generates the following warnings and error:

> WARNING: failed to set O_CLOEXEC flags on image    
> WARNING: failed to set O_CLOEXEC flags on image 
> ERROR  : Failed to set securebits: Invalid 
> ERROR  : Failed to set securebits: Invalid argument   

It would be great if you could help in resolving this issue.

**Comment by mrazekv** [comment]
Hi,
I am not sure about singularity support in WSL. Maybe you will have to build your own files using NVIDIA toolchain.

Firstly please check standard NVIDIA singularity container ( https://developer.nvidia.com/blog/how-to-run-ngc-deep-learning-containers-with-singularity/ )

```
singularity pull tensorflow-19.11-tf1-py3.sif docker://nvcr.io/nvidia/tensorflow:19.11-tf1-py3
```

**Comment by ayeshamkzhh** [comment]
Many thanks. I tried to build the files with the following commands: 

```
mkdir build
cd build
cmake .. -DTFAPPROX_CUDA_ARCHS="75"
make
```

I also run the above mentioned commands by replacing the cmake line with `cmake -DTFAPPROX_ALLOW_GPU_CONV=OFF` but it cannot file CMakeLists.txt inside the build folder. I checked the build folder but its not generated there.

However, when I try to run examples/fake_approx_train.py, it cannot find libApproxGPUOpsTF.so file. 

Moreover, the standard NVIDIA singularity container also generates the same error as stated in the previous comment.

**Comment by mrazekv** [comment]
Is `libApproxGPUOpsTF.so` file located in the `build` folder?

If **not**, please provide me an output of the build (cmake and make) commands

If **yes**, you should modify LDD_LIBRARY_PATH or modify https://github.com/ehw-fit/tf-approximate/blob/master/tf2/python/keras/layers/fake_approx_convolutional.py#L32 line 32 to provide a correct address to the SO file.

**Comment by ayeshamkzhh** [comment]
Many thanks. It worked after adding path for the `libApproxGPUOpsTF.so` file in `fake_approx_convolutional.py` file.
