### ISSUE TITLE
Any chance to change addition?

### ISSUE THREAD

**Issue by buraktoker** [ehw-fit/tf-approximate#14]
Hello,
First of all thanks for your work. This is important framework for who work approximate units. However, is there any chance or guidance to change only addition to approximate addition. I checked your code and it is made multiplication in axqconv.cc line:242. 
If I change total addition with
" total += 
                    axm -
                    static_cast<int32>(input_source_value) * filter_offset -
                    static_cast<int32>(filter_source_value) * input_offset +
                    input_offset * filter_offset;"

with approximate addition, is this a proper change?
Thanks in advance.

**Comment by mrazekv** [comment]
Hi @buraktoker 
thank you for your interest. The addition including is not as simple. The code, you posted, covers quantization constants too (the other items than `axm`). 

If you want to include approximate addition, you should add all `axm`s with approximate adder, and rest components with accurate adder. Then (after the for-loop) sum these variables to the `total`. But it would need more time for testing.

BR
Vojta

**Comment by buraktoker** [comment]
Thanks for answer,
Burak,
