### ISSUE TITLE
Singularity container download timing out

### ISSUE THREAD

**Issue by zois-tasoulas** [ehw-fit/tf-approximate#2]
Hi,

I am trying to download the singularity container for the GPU implementation.
Unfortunately, after 30 minutes of downloading the download stops with the following message:

`FATAL:   While pulling from image from http(s): context deadline exceeded (Client.Timeout or context cancellation while reading body)`

I tried looking at my singularity.conf file but cannot find a timeout configuration for the client.

**Comment by FilipVaverka** [comment]
I'm not sure how to change the timeout in Singularity. However it should be possible to download the container using **wget** (or even just navigate the URL with your web browser) instead. With the *.sif file downloaded you should be able to continue in the same way as if you were to use "sigularity pull ..." command.

**Comment by mrazekv** [comment]
We added a note to the README file.
