### ISSUE TITLE
[tf2]How to generate the binary lookup table of approximate multiplier?

### ISSUE THREAD

**Issue by johnzhou1996** [ehw-fit/tf-approximate#5]
Hi,
Thank you for your opening source very much.
I'd like to test the accuracy with my own approximate multipliers. Therefore, I wonder how to generate the multiplication table file.

**Comment by mrazekv** [comment]
Hi,
it is very easy in C. But you can also try to do it in different tool (the accurate 8-bit multiplier output should be exactly same as [tf2/examples/axmul_8x8/mul8u_1JFF.bin](/ehw-fit/tf-approximate/blob/master/tf2/examples/axmul_8x8/mul8u_1JFF.bin)

```c
FILE * f = fopen("output.bin", "wb");

for(unsigned int a = 0; a < 256; a++)
    for(unsigned int b = 0; b < 256; b++) {
      uint16_t val = approximate_mult(a, b); // replace by your own function call
      fwrite(&val, sizeof(uint16_t), 1, f);
    }

fclose(f);
```

**Comment by mrazekv** [comment]
I have included this example to  [the README file](https://github.com/ehw-fit/tf-approximate/tree/master/tf2#approximation-by-your-own-multiplier).

**Comment by pilipovicr** [comment]
Greetings, 

Can we employ approximate multipliers with different bit-widths?

**Comment by mrazekv** [comment]
The inputs of convolutional layers are quantized for 8 bits. If you want to simulate lower bit widths, you can simulate it as:

```c
int approximate_mult(int a, int b) {
   return (a & 0xFE) * (b & 0xFE); // for 7-bits
}
```

**Comment by pilipovicr** [comment]
Is it possible to quantize weights using higher bit-widths. In the code, I saw that you can adjust the the quantization parameter.

**Comment by FilipVaverka** [comment]
We have tried to keep the interface somewhat open to that possibility. However at the moment this is not supported as multiplication lookup tables would get too large very quickly and wouldn't fit into fast caches of the GPU.

**Comment by pilipovicr** [comment]
Thanks for response and thank you for publishing the code.
