### ISSUE TITLE
Gradient Implementation

### ISSUE THREAD

**Issue by AaronJing** [ehw-fit/tf-approximate#6]
Great Work! Just some questions. For the gradient part, I did not see the actual implementation for gradient operation, but only register using official implementation. If I missed it, please correct me. In this case, are you using approximation only in forwarding stage? Thanks.

**Comment by pilipovicr** [comment]
Related to the topic: Can you train the models with approximate layers (FakeApproxConv2D)?

**Comment by AaronJing** [comment]
Only support inference
