### ISSUE TITLE
Possible bug in IM2COL kernel

### ISSUE THREAD

**Issue by AaronJing** [ehw-fit/tf-approximate#7]
https://github.com/ehw-fit/tf-approximate/blob/6a726b95a1f040230692228ec33e393668084676/tf2/src/cuda/approx_nn_conv_kernels.cu#L602
The following two lines should be signed, right?

**Comment by FilipVaverka** [comment]
You are right, that is indeed a bug. I think, it shouldn't be catastrophic as underflow in "inH" and "inW" should be caught by upper bound check. Either way, we will fix it with next update.
